const String DATABASE_NOME = "projeto_TCC_db";

final createTableCanal = '''
CREATE TABLE CANAL(
UUID INTERGER PRIMARY KEY,
NOMECANAL VARCHAR(255),
VALORCUSTO  INTERGER,
HABILITADO INTERGER NOT NULL )
''';

final createTableProduto = '''
CREATE TABLE PRODUTO(
UUID INTERGER PRIMARY KEY,
NOMEPRODUTO VARCHAR(255),
VALORCUSTO  INTERGER )
''';

final createTableUsuario = '''
CREATE TABLE USUARIO(
UUID INTERGER PRIMARY KEY,
NOME VARCHAR(255),
SENHA  VARCHAR(255),
SALDO INTERGER NOT NULL )
''';

final createTableFinancas = '''
CREATE TABLE FINANCAS(
UUID INT PRIMARY KEY,
SALDO INTERGER NOT NULL )
''';



final createTableVenda  = '''
CREATE TABLE VENDA(
UUID INTERGER PRIMARY KEY,
UUIDUSUARIO VARCHAR(255),
UUIDPRODUTOCANAL VARCHAR(255),
QUANTIDADE INTERGER,
vALORUNIDADE INTERGER,
VALORTOTAL INTERGER)
''';

final createTableCompra  = '''
CREATE TABLE COMPRA(
UUID INTERGER PRIMARY KEY,
UUIDUSUARIO VARCHAR(255),
UUIDPRODUTOCANAL VARCHAR(255),
QUANTIDADE INTERGER,
VALORUNIDADE INTERGER,
VALORTOTAL INTERGER)
''';

final createTablePerguntas = '''
CREATE TABLE PERGUNTA(
UUID INT PRIMARY KEY,
SALDO INTERGER NOT NULL )
''';

final insert1 = '''
INSERT INTO USUARIO (UUID, NOME, SENHA, SALDO) VALUES ("0484fbb0-afcc-11ed-afa1-0242ac120002","leandro", "ando1992", 0)
''';



